<?xml version="1.0" encoding="UTF-8"?>
<testsuites tests="5" failures="1" disabled="0" errors="0" time="0." timestamp="2025-05-22T07:17:58.349" name="AllTests">
  <testsuite name="StringCalculatorTest" tests="5" failures="1" disabled="0" skipped="0" errors="0" time="0." timestamp="2025-05-22T07:17:58.349">
    <testcase name="TwoNumbersReturnSum" file="string_calculator_test.cpp" line="7" status="run" result="completed" time="0." timestamp="2025-05-22T07:17:58.349" classname="StringCalculatorTest" />
    <testcase name="MultipleNumbersReturnSum" file="string_calculator_test.cpp" line="13" status="run" result="completed" time="0." timestamp="2025-05-22T07:17:58.349" classname="StringCalculatorTest" />
    <testcase name="EmptyStringReturnsZero" file="string_calculator_test.cpp" line="19" status="run" result="completed" time="0." timestamp="2025-05-22T07:17:58.349" classname="StringCalculatorTest" />
    <testcase name="SingleNumberReturnsValue" file="string_calculator_test.cpp" line="24" status="run" result="completed" time="0." timestamp="2025-05-22T07:17:58.349" classname="StringCalculatorTest" />
    <testcase name="InvalidInputHandling" file="string_calculator_test.cpp" line="30" status="run" result="completed" time="0." timestamp="2025-05-22T07:17:58.349" classname="StringCalculatorTest">
      <failure message="unknown file&#x0A;C++ exception with description &quot;invalid stoi argument&quot; thrown in the test body.&#x0A;" type=""><![CDATA[unknown file
C++ exception with description "invalid stoi argument" thrown in the test body.
]]></failure>
    </testcase>
  </testsuite>
</testsuites>
